// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Game struct {
	ID   int64
	Name string
}

type Player struct {
	ID         int64
	PlayerID   string
	GameID     int64
	ReportedBy sql.NullString
	ReportedAt string
}
