// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const getPlayer = `-- name: GetPlayer :one
SELECT id, player_id, game_id, reported_by, reported_at
FROM players
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPlayer(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.GameID,
		&i.ReportedBy,
		&i.ReportedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, player_id, game_id, reported_by, reported_at
FROM players
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.GameID,
			&i.ReportedBy,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPlayer = `-- name: RegisterPlayer :one
INSERT INTO players (player_id, game_id, reported_by, reported_at)
VALUES (?, ?, ?, ?)
RETURNING id, player_id, game_id, reported_by, reported_at
`

type RegisterPlayerParams struct {
	PlayerID   string
	GameID     int64
	ReportedBy sql.NullString
	ReportedAt string
}

func (q *Queries) RegisterPlayer(ctx context.Context, arg RegisterPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, registerPlayer,
		arg.PlayerID,
		arg.GameID,
		arg.ReportedBy,
		arg.ReportedAt,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.GameID,
		&i.ReportedBy,
		&i.ReportedAt,
	)
	return i, err
}

const removePlayer = `-- name: RemovePlayer :exec
DELETE
FROM players
WHERE id = ?
`

func (q *Queries) RemovePlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removePlayer, id)
	return err
}
